<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Facades\DB; // Pour insérer les données

return new class extends Migration
{
    public function up()
    {
        Schema::create('menu_items', function (Blueprint $table) {
            $table->id();
            $table->foreignId('menu_id')->nullable()->constrained()->nullOnDelete();
            $table->foreignId('parent_id')->nullable()->constrained('menu_items')->nullOnDelete();
            $table->string('title');
            $table->string('url')->nullable();
            $table->string('route')->nullable();
            $table->string('policy')->nullable();
            $table->string('target')->default('_self');
            $table->string('icon_regular', 25)->nullable();
            $table->string('icon_solid', 25)->nullable();
            $table->integer('order');
            $table->text('parameters')->nullable();
            $table->timestamps();
            $table->softDeletes();
            
            $table->index(['menu_id', 'parent_id']);
        });
        DB::table('menu_items')->insert([
            [
                'id' => 25,
                'menu_id' => 1,
                'parent_id' => null,
                'title' => 'Gestion de tâches',
                'url' => 'regidoc.taches.index',
                'route' => 'Voir les taches',
                'policy' => null,
                'target' => '_self',
                'icon_regular' => 'fi fi-rr-list-check fi-rr',
                'icon_solid' => 'fi fi-sr-list-check fi-sr',
                'order' => 3,
                'parameters' => null,
                'created_at' => '2022-10-15 10:59:25',
                'updated_at' => '2022-10-15 10:59:25',
                'deleted_at' => null,
            ],
            [
                'id' => 28,
                'menu_id' => 1,
                'parent_id' => null,
                'title' => 'Employés',
                'url' => 'regidoc.personnels.index',
                'route' => 'Gerer les personnels',
                'policy' => null,
                'target' => '_self',
                'icon_regular' => 'fi fi-rr-users-alt fi-rr',
                'icon_solid' => 'fi fi-sr-users-alt fi-sr',
                'order' => 7,
                'parameters' => null,
                'created_at' => '2022-10-15 11:07:43',
                'updated_at' => '2022-10-15 11:07:43',
                'deleted_at' => null,
            ],
            [
                'id' => 40,
                'menu_id' => 1,
                'parent_id' => null,
                'title' => 'Paramètres',
                'url' => null,
                'route' => 'Voir les parametres',
                'policy' => null,
                'target' => '_self',
                'icon_regular' => 'fi fi-rr-settings fi-rr',
                'icon_solid' => 'fi fi-sr-settings fi-sr',
                'order' => 8,
                'parameters' => null,
                'created_at' => '2022-10-15 11:04:19',
                'updated_at' => '2022-10-15 11:04:19',
                'deleted_at' => null,
            ],
            [
                'id' => 48,
                'menu_id' => 1,
                'parent_id' => null,
                'title' => 'A-propos',
                'url' => '#',
                'route' => 'voir_le_menu_à_propos',
                'policy' => null,
                'target' => '_blank',
                'icon_regular' => 'fi fi-rr-info fi-rr',
                'icon_solid' => 'fi fi-sr-info fi-sr',
                'order' => 10,
                'parameters' => null,
                'created_at' => '2022-10-15 11:04:19',
                'updated_at' => '2022-10-15 11:04:19',
                'deleted_at' => '2023-07-10 07:09:10',
            ],
            [
                'id' => 52,
                'menu_id' => 1,
                'parent_id' => null,
                'title' => 'Archivage',
                'url' => 'regidoc.archivages.index',
                'route' => 'Voir les archives',
                'policy' => null,
                'target' => '_self',
                'icon_regular' => 'fi fi-rr-box fi-rr',
                'icon_solid' => 'fi fi-sr-box fi-sr',
                'order' => 5,
                'parameters' => null,
                'created_at' => '2022-10-15 11:04:19',
                'updated_at' => '2022-10-15 11:04:19',
                'deleted_at' => null,
            ],
            [
                'id' => 53,
                'menu_id' => 1,
                'parent_id' => null,
                'title' => 'Boîte de reception',
                'url' => 'regidoc.courriers.index',
                'route' => 'Voir les courriers',
                'policy' => null,
                'target' => '_self',
                'icon_regular' => 'fi fi-rr-envelope fi-rr',
                'icon_solid' => 'fi fi-sr-envelope fi-sr',
                'order' => 2,
                'parameters' => null,
                'created_at' => '2022-10-15 11:04:19',
                'updated_at' => '2022-10-15 11:04:19',
                'deleted_at' => null,
            ],
            [
                'id' => 54,
                'menu_id' => 1,
                'parent_id' => 40,
                'title' => 'Section',
                'url' => 'regidoc.sections.index',
                'route' => 'Voir les Sections',
                'policy' => null,
                'target' => '_self',
                'icon_regular' => 'fi fi-rr-building fi-rr',
                'icon_solid' => 'fi fi-sr-building fi-sr',
                'order' => 3,
                'parameters' => null,
                'created_at' => '2022-10-15 11:04:19',
                'updated_at' => '2022-10-15 11:04:19',
                'deleted_at' => null,
            ],
            [
                'id' => 55,
                'menu_id' => 1,
                'parent_id' => null,
                'title' => 'Tableau de bord',
                'url' => '/',
                'route' => 'regidoc.home',
                'policy' => null,
                'target' => '_self',
                'icon_regular' => 'fi fi-rr-apps fi-rr',
                'icon_solid' => 'fi fi-sr-apps fi-sr',
                'order' => 1,
                'parameters' => null,
                'created_at' => '2022-10-14 15:15:06',
                'updated_at' => '2022-10-14 15:15:06',
                'deleted_at' => null,
            ],
            [
                'id' => 56,
                'menu_id' => 1,
                'parent_id' => null,
                'title' => 'Chat',
                'url' => 'regidoc.chat.index',
                'route' => 'voir_les_messages',
                'policy' => null,
                'target' => '_self',
                'icon_regular' => 'fi fi-rr-comment fi-rr',
                'icon_solid' => 'fi fi-sr-comment fi-sr',
                'order' => 6,
                'parameters' => null,
                'created_at' => '2022-10-15 11:07:43',
                'updated_at' => '2022-10-15 11:07:43',
                'deleted_at' => '2023-07-09 23:00:00',
            ],
            [
                'id' => 57,
                'menu_id' => 1,
                'parent_id' => null,
                'title' => 'Documents',
                'url' => 'regidoc.documents.index',
                'route' => 'Voir les documents',
                'policy' => null,
                'target' => '_self',
                'icon_regular' => 'fi fi-rr-folder fi-rr',
                'icon_solid' => 'fi fi-sr-folder fi-sr',
                'order' => 4,
                'parameters' => null,
                'created_at' => '2022-10-14 15:15:06',
                'updated_at' => '2022-10-14 15:15:06',
                'deleted_at' => null,
            ],
            [
                'id' => 58,
                'menu_id' => 1,
                'parent_id' => 40,
                'title' => 'Directions',
                'url' => 'regidoc.directions.index',
                'route' => 'Voir les Directions',
                'policy' => null,
                'target' => '_self',
                'icon_regular' => 'fi fi-rr-building fi-rr',
                'icon_solid' => 'fi fi-sr-building fi-sr',
                'order' => 2,
                'parameters' => null,
                'created_at' => '2022-10-15 11:04:19',
                'updated_at' => '2022-10-15 11:04:19',
                'deleted_at' => null,
            ],
            [
                'id' => 59,
                'menu_id' => 1,
                'parent_id' => 40,
                'title' => 'Divisions',
                'url' => 'regidoc.divisions.index',
                'route' => 'Voir les Divisions',
                'policy' => null,
                'target' => '_self',
                'icon_regular' => 'fi fi-rr-building fi-rr',
                'icon_solid' => 'fi fi-sr-building fi-sr',
                'order' => 4,
                'parameters' => null,
                'created_at' => '2022-10-15 11:04:19',
                'updated_at' => '2022-10-15 11:04:19',
                'deleted_at' => null,
            ],
            [
                'id' => 60,
                'menu_id' => 1,
                'parent_id' => 40,
                'title' => 'Services',
                'url' => 'regidoc.services.index',
                'route' => 'Voir les Services',
                'policy' => null,
                'target' => '_self',
                'icon_regular' => 'fi fi-rr-building fi-rr',
                'icon_solid' => 'fi fi-sr-building fi-sr',
                'order' => 5,
                'parameters' => null,
                'created_at' => '2022-10-15 11:04:19',
                'updated_at' => '2022-10-15 11:04:19',
                'deleted_at' => null,
            ],
            [
                'id' => 61,
                'menu_id' => 1,
                'parent_id' => 40,
                'title' => 'Fonctions',
                'url' => 'regidoc.fonctions.index',
                'route' => 'Voir les Fonctions',
                'policy' => null,
                'target' => '_self',
                'icon_regular' => 'fi-rr-id-badge',
                'icon_solid' => 'fi-rr-id-badge',
                'order' => 6,
                'parameters' => null,
                'created_at' => '2022-10-15 11:04:19',
                'updated_at' => '2022-10-15 11:04:19',
                'deleted_at' => null,
            ],
            [
                'id' => 62,
                'menu_id' => 1,
                'parent_id' => 40,
                'title' => 'Grades',
                'url' => 'regidoc.grades.index',
                'route' => 'Voir les Grades',
                'policy' => null,
                'target' => '_self',
                'icon_regular' => 'fi fi-rr-building fi-rr',
                'icon_solid' => 'fi fi-sr-building fi-sr',
                'order' => 7,
                'parameters' => null,
                'created_at' => '2022-10-15 11:04:19',
                'updated_at' => '2022-10-15 11:04:19',
                'deleted_at' => null,
            ],
            [
                'id' => 63,
                'menu_id' => 1,
                'parent_id' => 40,
                'title' => "Lieu d'affectation",
                'url' => 'regidoc.lieux.index',
                'route' => "Voir les lieux d'affectations",
                'policy' => null,
                'target' => '_self',
                'icon_regular' => 'fi-rr-map-marker',
                'icon_solid' => 'fi-rr-map-marker',
                'order' => 1,
                'parameters' => null,
                'created_at' => '2022-10-15 11:04:19',
                'updated_at' => '2022-10-15 11:04:19',
                'deleted_at' => null,
            ],
            [
                'id' => 64,
                'menu_id' => 1,
                'parent_id' => 40,
                'title' => 'Secretariat',
                'url' => 'regidoc.secretariats.index',
                'route' => 'Voir les Secretaires',
                'policy' => null,
                'target' => '_self',
                'icon_regular' => 'fi fi-rr-building fi-rr',
                'icon_solid' => 'fi fi-sr-building fi-sr',
                'order' => 3,
                'parameters' => null,
                'created_at' => '2022-10-15 11:04:19',
                'updated_at' => '2022-10-15 11:04:19',
                'deleted_at' => null,
            ],
            [
                'id' => 65,
                'menu_id' => 1,
                'parent_id' => 40,
                'title' => 'Assistanat',
                'url' => 'regidoc.assistants.index',
                'route' => 'Voir les Assistants',
                'policy' => null,
                'target' => '_self',
                'icon_regular' => 'fi-rr-headset',
                'icon_solid' => 'fi-rr-headset',
                'order' => 4,
                'parameters' => null,
                'created_at' => '2022-10-15 11:04:19',
                'updated_at' => '2022-10-15 11:04:19',
                'deleted_at' => null,
            ],
            [
                'id' => 66,
                'menu_id' => 1,
                'parent_id' => 40,
                'title' => 'Sessions Log',
                'url' => 'regidoc.session',
                'route' => "Voir l'historique des sessions",
                'policy' => null,
                'target' => '_self',
                'icon_regular' => 'fi fi-rr-building fi-rr',
                'icon_solid' => 'fi fi-sr-building fi-sr',
                'order' => 11,
                'parameters' => null,
                'created_at' => '2022-10-15 11:04:19',
                'updated_at' => '2022-10-15 11:04:19',
                'deleted_at' => '2023-09-22 20:42:58',
            ],
            [
                'id' => 67,
                'menu_id' => 1,
                'parent_id' => 40,
                'title' => 'Catégories',
                'url' => 'regidoc.categories.index',
                'route' => null,
                'policy' => null,
                'target' => '_self',
                'icon_regular' => 'fi-rr-file',
                'icon_solid' => 'fi-rr-file',
                'order' => 8,
                'parameters' => null,
                'created_at' => '2025-08-05 18:49:22',
                'updated_at' => '2025-08-05 18:49:22',
                'deleted_at' => null,
            ],
            [
                'id' => 68,
                'menu_id' => 1,
                'parent_id' => 40,
                'title' => 'Expéditeurs',
                'url' => 'regidoc.expediteurs.index',
                'route' => null,
                'policy' => null,
                'target' => '_self',
                'icon_regular' => 'fi-rr-envelope',
                'icon_solid' => 'fi-rr-envelope',
                'order' => 9,
                'parameters' => null,
                'created_at' => '2025-08-05 18:49:22',
                'updated_at' => '2025-08-05 18:49:22',
                'deleted_at' => null,
            ],
            [
                'id' => 69,
                'menu_id' => 1,
                'parent_id' => 40,
                'title' => 'Natures',
                'url' => 'regidoc.natures.index',
                'route' => null,
                'policy' => null,
                'target' => '_self',
                'icon_regular' => 'fi-rr-document',
                'icon_solid' => 'fi-rr-document',
                'order' => 10,
                'parameters' => null,
                'created_at' => '2025-08-05 18:49:22',
                'updated_at' => '2025-08-05 18:49:22',
                'deleted_at' => null,
            ],
        ]);
        

    }

    public function down()
    {
        Schema::dropIfExists('menu_items');
    }
};
